name: IDMMac
options:
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
packages:
  DownloadEngine:
    path: ./DownloadEngine
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    exactVersion: 2.6.4
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.ahmedsam.idmmac
    DEVELOPMENT_TEAM: ""
    SWIFT_VERSION: 5.9
    CURRENT_PROJECT_VERSION: 3
    MARKETING_VERSION: 0.2.0
    CODE_SIGN_STYLE: Automatic
targets:
  IDMMacApp:
    type: application
    platform: macOS
    sources:
      - path: IDMMacApp
      - path: Tools/ChromeExtension
    dependencies:
      - package: DownloadEngine
        product: DownloadEngine
      - package: Sparkle
        product: Sparkle
    settings:
      base:
        INFOPLIST_FILE: IDMMacApp/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: IDMMacApp/App/IDMMacApp.entitlements
      configs:
        Release:
          ENABLE_HARDENED_RUNTIME: YES
        
    scheme:
      testTargets: []

