name: IDMMac
options:
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
packages:
  DownloadEngine:
    path: /Users/ahmed/Documents/IDMMac/DownloadEngine
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.example.idmmac
    DEVELOPMENT_TEAM: ""
    SWIFT_VERSION: 5.9
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 0.1.0
    CODE_SIGN_STYLE: Automatic
targets:
  IDMMacApp:
    type: application
    platform: macOS
    sources:
      - path: IDMMacApp
      - path: Tools/ChromeExtension
    dependencies:
      - package: DownloadEngine
        product: DownloadEngine
    settings:
      base:
        INFOPLIST_FILE: IDMMacApp/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: IDMMacApp/App/IDMMacApp.entitlements
        
    scheme:
      testTargets: []

