# This workflow will build the IDMMac Xcode project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build IDMMac

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
    
    - name: Build Xcode Project
      run: xcodebuild -project IDMMac.xcodeproj -scheme IDMMacApp -configuration Release -destination 'platform=macOS' build
