# This workflow will build the NanoJet Xcode project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build NanoJet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
    
    - name: Install XcodeGen
      run: brew install xcodegen
    
    - name: Generate Xcode Project
      run: xcodegen generate
    
    - name: Build Xcode Project
      run: xcodebuild -project NanoJet.xcodeproj -scheme NanoJetApp -configuration Release -destination 'platform=macOS' build
